services:
    gallformers:
        platform: ${BUILD_PLATFORM:-linux/amd64}
        build:
            context: .
            dockerfile: ./Dockerfile
            platforms:
                - ${BUILD_PLATFORM:-linux/amd64}
        image: gallformers:latest
        container_name: gallformer_app
        restart: unless-stopped
        environment:
            PORT: 3000
        command: yarn start
        x-bake:
            platforms:
                - ${BUILD_PLATFORM:-linux/amd64}
            output:
                - type=docker
                  dest=./gallformers-docker.tar
                - type=docker
                  dest=./gallformers:latest
    