version: '3.7'

services:
    gallformers:
        platform: linux/amd64
        build:
            context: .
            dockerfile: ./Dockerfile
        image: gallformers:latest
        container_name: gallformer_app
        restart: unless-stopped
        environment:
            PORT: 3000
        command: yarn start
        x-bake:
            platforms:
                - linux/amd64
    