app = "gallformers-staging"
primary_region = "iad"

[build]
dockerfile = 'Dockerfile.fly'

[env]
NODE_ENV = "production"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[[http_service.checks]]
interval = "10s"
grace_period = "5s"
method = "get"
path = "/api/health"
timeout = "2s"

[http_service.checks.headers]
User-Agent = "fly-health-check-staging"

[[mounts]]
source = "gallformers_staging_data"
destination = "/data"

[vm]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
