# fly.toml app configuration file generated for gallformers on 2025-01-19T14:10:38-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gallformers'
primary_region = 'iad'

[build]

[processes]
  app = 'node ./dbsetup.js yarn start'

[[mounts]]
  source = 'data'
  destination = '/data'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = '1GB'
  auto_extend_size_limit = '10GB'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
