defmodule GallformersWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :gallformers

  # The session is stored in the cookie, signed and encrypted.
  # secure: true is set in production only (dev/test use HTTP).
  @session_options [
    store: :cookie,
    key: "_gallformers_key",
    signing_salt: "Z2Zo8q/D",
    encryption_salt: "pP9YsGAhNA8=",
    same_site: "Lax",
    secure: Application.compile_env(:gallformers, :env) == :prod
  ]

  # log: :debug suppresses "CONNECTED TO Phoenix.LiveView.Socket" noise in prod logs
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], log: :debug],
    longpoll: [connect_info: [session: @session_options], log: :debug]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :gallformers,
    gzip: not code_reloading?,
    only: GallformersWeb.static_dirs(),
    only_matching: GallformersWeb.static_matching(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :gallformers
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # Rewrite host from X-Forwarded-Host header when behind CloudFront/proxy
  # This ensures OAuth callbacks use the correct host
  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug GallformersWeb.Router
end
