import Config

config :gallformers, env: :prod

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :gallformers, GallformersWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# SSL is handled by Fly.io's proxy (force_https = true in fly.toml).
# We don't use Phoenix force_ssl since it breaks internal health checks.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Ueberauth callback URL must be set at compile time (Ueberauth.init runs at compile time)
# This overrides the default behavior of using the request's host
config :ueberauth, Ueberauth,
  providers: [
    auth0:
      {Ueberauth.Strategy.Auth0,
       [callback_url: "https://www.gallformers.org/auth/auth0/callback"]}
  ]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
