-- Generate a self-contained SQL transaction that restores one deleted gall.
--
-- Run against the full backup restored in gallformers_dev:
--   psql -X -qAt -v ON_ERROR_STOP=1 -v gall_id="$GALL_ID" \
--     -d gallformers_dev \
--     -f runbooks/sql/generate-deleted-gall-restore.sql \
--     > "$RECOVERY_ROOT/restore-gall.sql"
--
-- The generated file is intended to run first against an isolated copy of
-- current production and then, unchanged, against production.

\set ON_ERROR_STOP on
\if :{?gall_id}
\else
  \echo 'ERROR: gall_id is required; pass -v gall_id=<integer>'
  DO $$ BEGIN RAISE EXCEPTION 'gall_id is required'; END $$;
\endif

BEGIN;

CREATE TEMP TABLE recovery_target (
  gall_id bigint PRIMARY KEY
) ON COMMIT DROP;

INSERT INTO recovery_target (gall_id) VALUES (:'gall_id');

DO $$
DECLARE
  target_id bigint;
  gall_count integer;
  trait_count integer;
BEGIN
  SELECT gall_id INTO target_id FROM recovery_target;

  SELECT count(*) INTO gall_count
  FROM public.species
  WHERE id = target_id AND taxoncode = 'gall';

  IF gall_count <> 1 THEN
    RAISE EXCEPTION 'expected one gall with species.id %, found %', target_id, gall_count;
  END IF;

  SELECT count(*) INTO trait_count
  FROM public.gall_traits
  WHERE species_id = target_id;

  IF trait_count <> 1 THEN
    RAISE EXCEPTION 'expected one gall_traits row for species.id %, found %',
      target_id, trait_count;
  END IF;
END $$;

-- Fail rather than silently omit a species dependency added after this
-- generator was written. SET NULL relationships also require separate curator
-- review because their rows survive deletion and cannot be restored by INSERT.
CREATE TEMP TABLE supported_species_references (
  table_name text NOT NULL,
  column_name text NOT NULL,
  PRIMARY KEY (table_name, column_name)
) ON COMMIT DROP;

INSERT INTO supported_species_references (table_name, column_name) VALUES
  ('alias_species', 'species_id'),
  ('gall_alignment', 'species_id'),
  ('gall_cells', 'species_id'),
  ('gall_color', 'species_id'),
  ('gall_form', 'species_id'),
  ('gall_plant_part', 'species_id'),
  ('gall_range', 'species_id'),
  ('gall_season', 'species_id'),
  ('gall_shape', 'species_id'),
  ('gall_texture', 'species_id'),
  ('gall_traits', 'species_id'),
  ('gall_walls', 'species_id'),
  ('gallhost', 'gall_species_id'),
  ('image', 'species_id'),
  ('species_source', 'species_id'),
  ('species_taxonomy', 'species_id');

DO $$
DECLARE
  fk record;
  target_id bigint;
  matching_rows bigint;
BEGIN
  SELECT gall_id INTO target_id FROM recovery_target;

  FOR fk IN
    SELECT
      ns.nspname AS schema_name,
      cls.relname AS table_name,
      att.attname AS column_name,
      con.conname AS constraint_name,
      con.confdeltype AS delete_action
    FROM pg_constraint con
    JOIN pg_class cls ON cls.oid = con.conrelid
    JOIN pg_namespace ns ON ns.oid = cls.relnamespace
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid
      AND att.attnum = con.conkey[1]
      AND NOT att.attisdropped
    WHERE con.contype = 'f'
      AND con.confrelid = 'public.species'::regclass
      AND cardinality(con.conkey) = 1
      AND ns.nspname = 'public'
  LOOP
    EXECUTE format(
      'SELECT count(*) FROM %I.%I WHERE %I = $1',
      fk.schema_name,
      fk.table_name,
      fk.column_name
    ) INTO matching_rows USING target_id;

    IF matching_rows > 0 AND NOT EXISTS (
      SELECT 1
      FROM supported_species_references supported
      WHERE supported.table_name = fk.table_name
        AND supported.column_name = fk.column_name
    ) THEN
      RAISE EXCEPTION
        'unsupported dependency: %.% via % has % row(s) for gall % (delete action %)',
        fk.table_name,
        fk.column_name,
        fk.constraint_name,
        matching_rows,
        target_id,
        fk.delete_action;
    END IF;
  END LOOP;
END $$;

CREATE TEMP TABLE restore_lines (
  position bigint PRIMARY KEY,
  sql text NOT NULL
) ON COMMIT DROP;

INSERT INTO restore_lines (position, sql) VALUES
  (1, E'\\set ON_ERROR_STOP on'),
  (2, '-- Generated by runbooks/sql/generate-deleted-gall-restore.sql'),
  (3, format('-- Gall species ID: %s', (SELECT gall_id FROM recovery_target))),
  (4, 'BEGIN;'),
  (5, 'SET LOCAL lock_timeout = ''5s'';');

-- Aliases are the only conditional inserts. The application may have retained
-- an alias because another species still uses it. If the ID exists, require the
-- complete row to match the backup; otherwise insert the backup row.
INSERT INTO restore_lines (position, sql)
SELECT
  1000 + row_number() OVER (ORDER BY a.id) * 2,
  format(
    'DO $alias_check$ BEGIN IF EXISTS (SELECT 1 FROM public.alias a WHERE a.id = %s AND to_jsonb(a) IS DISTINCT FROM %L::jsonb) THEN RAISE EXCEPTION ''alias ID %s differs from backup''; END IF; END $alias_check$;',
    a.id,
    to_jsonb(a)::text,
    a.id
  )
FROM public.alias a
JOIN public.alias_species als ON als.alias_id = a.id
JOIN recovery_target target ON target.gall_id = als.species_id;

INSERT INTO restore_lines (position, sql)
SELECT
  1001 + row_number() OVER (ORDER BY a.id) * 2,
  format(
    'INSERT INTO public.alias SELECT * FROM jsonb_populate_record(NULL::public.alias, %L::jsonb) WHERE NOT EXISTS (SELECT 1 FROM public.alias WHERE id = %s);',
    to_jsonb(a)::text,
    a.id
  )
FROM public.alias a
JOIN public.alias_species als ON als.alias_id = a.id
JOIN recovery_target target ON target.gall_id = als.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 2000, format(
  'INSERT INTO public.species SELECT * FROM jsonb_populate_record(NULL::public.species, %L::jsonb);',
  to_jsonb(s)::text
)
FROM public.species s
JOIN recovery_target target ON target.gall_id = s.id;

INSERT INTO restore_lines (position, sql)
SELECT 3000, format(
  'INSERT INTO public.gall_traits SELECT * FROM jsonb_populate_record(NULL::public.gall_traits, %L::jsonb);',
  to_jsonb(gt)::text
)
FROM public.gall_traits gt
JOIN recovery_target target ON target.gall_id = gt.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 4000 + row_number() OVER (ORDER BY to_jsonb(als)::text), format(
  'INSERT INTO public.alias_species SELECT * FROM jsonb_populate_record(NULL::public.alias_species, %L::jsonb);',
  to_jsonb(als)::text
)
FROM public.alias_species als
JOIN recovery_target target ON target.gall_id = als.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 5000 + row_number() OVER (ORDER BY to_jsonb(st)::text), format(
  'INSERT INTO public.species_taxonomy SELECT * FROM jsonb_populate_record(NULL::public.species_taxonomy, %L::jsonb);',
  to_jsonb(st)::text
)
FROM public.species_taxonomy st
JOIN recovery_target target ON target.gall_id = st.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 6000 + row_number() OVER (ORDER BY gh.id), format(
  'INSERT INTO public.gallhost SELECT * FROM jsonb_populate_record(NULL::public.gallhost, %L::jsonb);',
  to_jsonb(gh)::text
)
FROM public.gallhost gh
JOIN recovery_target target ON target.gall_id = gh.gall_species_id;

INSERT INTO restore_lines (position, sql)
SELECT 7000 + row_number() OVER (ORDER BY to_jsonb(gr)::text), format(
  'INSERT INTO public.gall_range SELECT * FROM jsonb_populate_record(NULL::public.gall_range, %L::jsonb);',
  to_jsonb(gr)::text
)
FROM public.gall_range gr
JOIN recovery_target target ON target.gall_id = gr.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 8000 + row_number() OVER (ORDER BY to_jsonb(gc)::text), format(
  'INSERT INTO public.gall_color SELECT * FROM jsonb_populate_record(NULL::public.gall_color, %L::jsonb);',
  to_jsonb(gc)::text
)
FROM public.gall_color gc
JOIN recovery_target target ON target.gall_id = gc.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 9000 + row_number() OVER (ORDER BY to_jsonb(gw)::text), format(
  'INSERT INTO public.gall_walls SELECT * FROM jsonb_populate_record(NULL::public.gall_walls, %L::jsonb);',
  to_jsonb(gw)::text
)
FROM public.gall_walls gw
JOIN recovery_target target ON target.gall_id = gw.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 10000 + row_number() OVER (ORDER BY to_jsonb(gc)::text), format(
  'INSERT INTO public.gall_cells SELECT * FROM jsonb_populate_record(NULL::public.gall_cells, %L::jsonb);',
  to_jsonb(gc)::text
)
FROM public.gall_cells gc
JOIN recovery_target target ON target.gall_id = gc.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 11000 + row_number() OVER (ORDER BY to_jsonb(gs)::text), format(
  'INSERT INTO public.gall_shape SELECT * FROM jsonb_populate_record(NULL::public.gall_shape, %L::jsonb);',
  to_jsonb(gs)::text
)
FROM public.gall_shape gs
JOIN recovery_target target ON target.gall_id = gs.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 12000 + row_number() OVER (ORDER BY to_jsonb(gt)::text), format(
  'INSERT INTO public.gall_texture SELECT * FROM jsonb_populate_record(NULL::public.gall_texture, %L::jsonb);',
  to_jsonb(gt)::text
)
FROM public.gall_texture gt
JOIN recovery_target target ON target.gall_id = gt.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 13000 + row_number() OVER (ORDER BY to_jsonb(ga)::text), format(
  'INSERT INTO public.gall_alignment SELECT * FROM jsonb_populate_record(NULL::public.gall_alignment, %L::jsonb);',
  to_jsonb(ga)::text
)
FROM public.gall_alignment ga
JOIN recovery_target target ON target.gall_id = ga.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 14000 + row_number() OVER (ORDER BY to_jsonb(gp)::text), format(
  'INSERT INTO public.gall_plant_part SELECT * FROM jsonb_populate_record(NULL::public.gall_plant_part, %L::jsonb);',
  to_jsonb(gp)::text
)
FROM public.gall_plant_part gp
JOIN recovery_target target ON target.gall_id = gp.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 15000 + row_number() OVER (ORDER BY to_jsonb(gf)::text), format(
  'INSERT INTO public.gall_form SELECT * FROM jsonb_populate_record(NULL::public.gall_form, %L::jsonb);',
  to_jsonb(gf)::text
)
FROM public.gall_form gf
JOIN recovery_target target ON target.gall_id = gf.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 16000 + row_number() OVER (ORDER BY to_jsonb(gs)::text), format(
  'INSERT INTO public.gall_season SELECT * FROM jsonb_populate_record(NULL::public.gall_season, %L::jsonb);',
  to_jsonb(gs)::text
)
FROM public.gall_season gs
JOIN recovery_target target ON target.gall_id = gs.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 17000 + row_number() OVER (ORDER BY ss.id), format(
  'INSERT INTO public.species_source SELECT * FROM jsonb_populate_record(NULL::public.species_source, %L::jsonb);',
  to_jsonb(ss)::text
)
FROM public.species_source ss
JOIN recovery_target target ON target.gall_id = ss.species_id;

INSERT INTO restore_lines (position, sql)
SELECT 18000 + row_number() OVER (ORDER BY i.id), format(
  'INSERT INTO public.image SELECT * FROM jsonb_populate_record(NULL::public.image, %L::jsonb);',
  to_jsonb(i)::text
)
FROM public.image i
JOIN recovery_target target ON target.gall_id = i.species_id;

-- Keep sequences at least as high as their current last value and table maximum.
-- Deleted IDs normally need no adjustment because deletion does not rewind a
-- sequence; these statements make that invariant explicit and safe.
INSERT INTO restore_lines (position, sql) VALUES
  (19000, 'SELECT setval(pg_get_serial_sequence(''public.species'', ''id''), GREATEST((SELECT max(id) FROM public.species), pg_sequence_last_value(pg_get_serial_sequence(''public.species'', ''id'')::regclass)), true);'),
  (19001, 'SELECT setval(pg_get_serial_sequence(''public.alias'', ''id''), GREATEST((SELECT max(id) FROM public.alias), pg_sequence_last_value(pg_get_serial_sequence(''public.alias'', ''id'')::regclass)), true);'),
  (19002, 'SELECT setval(pg_get_serial_sequence(''public.image'', ''id''), GREATEST((SELECT max(id) FROM public.image), pg_sequence_last_value(pg_get_serial_sequence(''public.image'', ''id'')::regclass)), true);'),
  (19003, 'SELECT setval(pg_get_serial_sequence(''public.gallhost'', ''id''), GREATEST((SELECT max(id) FROM public.gallhost), pg_sequence_last_value(pg_get_serial_sequence(''public.gallhost'', ''id'')::regclass)), true);'),
  (19004, 'SELECT setval(pg_get_serial_sequence(''public.species_source'', ''id''), GREATEST((SELECT max(id) FROM public.species_source), pg_sequence_last_value(pg_get_serial_sequence(''public.species_source'', ''id'')::regclass)), true);'),
  (20000, 'COMMIT;');

SELECT sql
FROM restore_lines
ORDER BY position;

ROLLBACK;
